image: node:gallium-alpine3.16

options:
  max-time: 15

pipelines:
  branches:
    develop:
      - step:
          name: Deploy API
          deployment: live
          caches:
            - node
          script:
            - cd api
            - npm ci
            - npx serverless deploy --stage $ENVIRONMENT --region $AWS_REGION

  custom:
    remove-live-api:
      - step:
          name: Remove Stage API
          deployment: live
          caches:
            - node
          script:
            - cd api
            - npm ci
            - npx serverless remove --stage $ENVIRONMENT --region $AWS_REGION
